pip install -e ~/source/edc-base
pip install -e ~/source/django-crypto-fields
pip install -e ~/source/django-revision
pip install -e ~/source/edc-appointment
pip install -e ~/source/edc-call-manager
pip install -e ~/source/edc-consent
pip install -e ~/source/edc-constants
pip install -e ~/source/edc-content-type-map
pip install -e ~/source/edc-dashboard
pip install -e ~/source/edc-data-manager
pip install -e ~/source/edc-death-report
pip install -e ~/source/edc-device
pip install -e ~/source/edc-export
pip install -e ~/source/edc-identifier
pip install -e ~/source/edc-lab
pip install -e ~/source/edc-label
pip install -e ~/source/edc-locator
pip install -e ~/source/edc-meta-data
pip install -e ~/source/edc-notification
pip install -e ~/source/edc-offstudy
pip install -e ~/source/edc-registration
pip install -e ~/source/edc-rest
pip install -e ~/source/edc-rule-groups
pip install -e ~/source/edc-sync
pip install -e ~/source/edc-templates
pip install -e ~/source/edc-visit-schedule
pip install -e ~/source/edc-visit-tracking
pip install -e ~/source/lab-requisition
pip install -e ~/source/lis
pip install -e ~/source/edc-code-lists
pip install -e ~/source/edc-configuration

