# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-07 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('td_infant', '0002_auto_20160507_1408'),
        ('lab_clinic_api', '__first__'),
        ('td_lab', '0001_initial'),
        ('td_maternal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maternalrequisition',
            name='maternal_visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='td_maternal.MaternalVisit'),
        ),
        migrations.AddField(
            model_name='maternalrequisition',
            name='packing_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='td_lab.PackingList'),
        ),
        migrations.AddField(
            model_name='maternalrequisition',
            name='panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='td_lab.Panel'),
        ),
        migrations.AddField(
            model_name='maternalrequisition',
            name='test_code',
            field=models.ManyToManyField(blank=True, null=True, to='lab_clinic_api.TestCode', verbose_name='Additional tests'),
        ),
        migrations.AddField(
            model_name='infantrequisition',
            name='aliquot_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='td_lab.AliquotType'),
        ),
        migrations.AddField(
            model_name='infantrequisition',
            name='infant_visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='td_infant.InfantVisit'),
        ),
        migrations.AddField(
            model_name='infantrequisition',
            name='packing_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='td_lab.PackingList'),
        ),
        migrations.AddField(
            model_name='infantrequisition',
            name='panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='td_lab.Panel'),
        ),
        migrations.AddField(
            model_name='infantrequisition',
            name='test_code',
            field=models.ManyToManyField(blank=True, null=True, to='lab_clinic_api.TestCode', verbose_name='Additional tests'),
        ),
        migrations.AddField(
            model_name='aliquotprofileitem',
            name='aliquot_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='td_lab.AliquotType'),
        ),
        migrations.AddField(
            model_name='aliquotprofileitem',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='td_lab.AliquotProfile'),
        ),
        migrations.AddField(
            model_name='aliquotprofile',
            name='aliquot_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='td_lab.AliquotType', verbose_name='Source aliquot type'),
        ),
        migrations.AddField(
            model_name='aliquotprocessing',
            name='aliquot',
            field=models.ForeignKey(help_text='Create aliquots from this one.', on_delete=django.db.models.deletion.CASCADE, to='td_lab.Aliquot', verbose_name='Source Aliquot'),
        ),
        migrations.AddField(
            model_name='aliquotprocessing',
            name='profile',
            field=models.ForeignKey(help_text='Create aliquots according to this profile.', on_delete=django.db.models.deletion.CASCADE, to='td_lab.AliquotProfile', verbose_name='Profile'),
        ),
        migrations.AddField(
            model_name='aliquot',
            name='aliquot_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='td_lab.AliquotCondition', verbose_name='Aliquot Condition'),
        ),
        migrations.AddField(
            model_name='aliquot',
            name='aliquot_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='td_lab.AliquotType', verbose_name='Aliquot Type'),
        ),
        migrations.AddField(
            model_name='aliquot',
            name='primary_aliquot',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary', to='td_lab.Aliquot'),
        ),
        migrations.AddField(
            model_name='aliquot',
            name='receive',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='td_lab.Receive'),
        ),
        migrations.AddField(
            model_name='aliquot',
            name='source_aliquot',
            field=models.ForeignKey(editable=False, help_text='Aliquot from which this aliquot was created, Leave blank if this is the primary tube', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source', to='td_lab.Aliquot'),
        ),
        migrations.AlterUniqueTogether(
            name='maternalrequisition',
            unique_together=set([('maternal_visit', 'panel', 'is_drawn')]),
        ),
        migrations.AlterUniqueTogether(
            name='infantrequisition',
            unique_together=set([('infant_visit', 'panel', 'is_drawn')]),
        ),
        migrations.AlterUniqueTogether(
            name='aliquotprofileitem',
            unique_together=set([('profile', 'aliquot_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='aliquot',
            unique_together=set([('receive', 'count')]),
        ),
    ]
