# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-11 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import django_extensions.db.fields
import django_revision.revision_field
import edc_base.model.fields.hostname_modification_field
import edc_base.model.fields.userfield
import edc_base.model.fields.uuid_auto_field
import edc_base.model.validators.date


class Migration(migrations.Migration):

    dependencies = [
        ('td_maternal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaternalUltraSoundFu',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('user_created', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(default='One-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50)),
                ('hostname_modified', edc_base.model.fields.hostname_modification_field.HostnameModificationField(editable=False, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('id', edc_base.model.fields.uuid_auto_field.UUIDAutoField(editable=False, help_text='System field. UUID primary key.', primary_key=True, serialize=False)),
                ('consent_version', models.CharField(default='?', editable=False, max_length=10)),
                ('report_datetime', models.DateTimeField(default=django.utils.timezone.now, help_text="If reporting today, use today's date/time, otherwise use the date/time this information was reported.", validators=[edc_base.model.validators.date.datetime_not_before_study_start, edc_base.model.validators.date.datetime_not_future], verbose_name='Report Date')),
                ('exported', models.BooleanField(default=False, editable=False, help_text="system field for export tracking. considered 'exported' if both sent and received.")),
                ('exported_datetime', models.DateTimeField(editable=False, help_text='system field for export tracking.', null=True)),
                ('export_change_type', models.CharField(choices=[('I', 'Insert'), ('U', 'Update'), ('D', 'Delete')], default='I', editable=False, help_text='system field for export tracking.', max_length=1)),
                ('export_uuid', django_extensions.db.fields.UUIDField(blank=True, editable=False, help_text='system field for export tracking.')),
                ('bpd', models.DecimalField(decimal_places=2, help_text='Units in mm.', max_digits=6, verbose_name='BDP?')),
                ('hc', models.DecimalField(decimal_places=2, help_text='Units in mm.', max_digits=6, verbose_name='HC?')),
                ('ac', models.DecimalField(decimal_places=2, help_text='Units in mm.', max_digits=6, verbose_name='AC?')),
                ('fl', models.DecimalField(decimal_places=2, help_text='Units in mm.', max_digits=6, verbose_name='FL?')),
                ('hl', models.DecimalField(decimal_places=2, help_text='Units in mm.', max_digits=6, verbose_name='HL?')),
                ('lateral_ventricle', models.DecimalField(decimal_places=2, help_text='Units in mm.', max_digits=6, verbose_name='Lateral Ventricle')),
                ('cerebellum', models.DecimalField(decimal_places=2, help_text='Units in mm.', max_digits=6, verbose_name='Cerebellum?')),
                ('cistema_magna', models.DecimalField(decimal_places=2, help_text='Units in mm.', max_digits=6, verbose_name='Cistema Magna')),
                ('malformations', models.CharField(choices=[('choroid_plexus_cyst', 'choroid plexus cyst'), ('intracranial_calcification', 'intracranial calcification'), ('posterior_fossa_cyst', 'posterior fossa cyst'), ('intracranial_cyst', 'intracranial cyst')], max_length=3, verbose_name='Amniotic fluid volume?')),
                ('maternal_visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='td_maternal.MaternalVisit')),
            ],
            options={
                'verbose_name': 'Maternal Ultra Sound Follow Up',
            },
            managers=[
                ('entry_meta_data_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MaternalUltraSoundInitial',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('user_created', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(default='One-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50)),
                ('hostname_modified', edc_base.model.fields.hostname_modification_field.HostnameModificationField(editable=False, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('id', edc_base.model.fields.uuid_auto_field.UUIDAutoField(editable=False, help_text='System field. UUID primary key.', primary_key=True, serialize=False)),
                ('consent_version', models.CharField(default='?', editable=False, max_length=10)),
                ('report_datetime', models.DateTimeField(default=django.utils.timezone.now, help_text="If reporting today, use today's date/time, otherwise use the date/time this information was reported.", validators=[edc_base.model.validators.date.datetime_not_before_study_start, edc_base.model.validators.date.datetime_not_future], verbose_name='Report Date')),
                ('exported', models.BooleanField(default=False, editable=False, help_text="system field for export tracking. considered 'exported' if both sent and received.")),
                ('exported_datetime', models.DateTimeField(editable=False, help_text='system field for export tracking.', null=True)),
                ('export_change_type', models.CharField(choices=[('I', 'Insert'), ('U', 'Update'), ('D', 'Delete')], default='I', editable=False, help_text='system field for export tracking.', max_length=1)),
                ('export_uuid', django_extensions.db.fields.UUIDField(blank=True, editable=False, help_text='system field for export tracking.')),
                ('bpd', models.DecimalField(decimal_places=2, help_text='Units in mm.', max_digits=6, verbose_name='BDP?')),
                ('hc', models.DecimalField(decimal_places=2, help_text='Units in mm.', max_digits=6, verbose_name='HC?')),
                ('ac', models.DecimalField(decimal_places=2, help_text='Units in mm.', max_digits=6, verbose_name='AC?')),
                ('fl', models.DecimalField(decimal_places=2, help_text='Units in mm.', max_digits=6, verbose_name='FL?')),
                ('hl', models.DecimalField(decimal_places=2, help_text='Units in mm.', max_digits=6, verbose_name='HL?')),
                ('lateral_ventricle', models.DecimalField(decimal_places=2, help_text='Units in mm.', max_digits=6, verbose_name='Lateral Ventricle')),
                ('cerebellum', models.DecimalField(decimal_places=2, help_text='Units in mm.', max_digits=6, verbose_name='Cerebellum?')),
                ('cistema_magna', models.DecimalField(decimal_places=2, help_text='Units in mm.', max_digits=6, verbose_name='Cistema Magna')),
                ('malformations', models.CharField(choices=[('choroid_plexus_cyst', 'choroid plexus cyst'), ('intracranial_calcification', 'intracranial calcification'), ('posterior_fossa_cyst', 'posterior fossa cyst'), ('intracranial_cyst', 'intracranial cyst')], max_length=3, verbose_name='Amniotic fluid volume?')),
                ('number_of_gestations', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('>3', 'greater than 3')], help_text='If number is not equal to 1, then participant goes off study.', max_length=3, verbose_name='Number of viable gestations seen?')),
                ('ga_by_lmp', models.IntegerField(verbose_name='GA by LMP at ultrasound date')),
                ('ga_by_ultrasound_wks', models.IntegerField(help_text='Units in weeks.', verbose_name='GA by ultrasound in weeks')),
                ('ga_by_ultrasound_days', models.IntegerField(help_text='must be less than 7days.', verbose_name='GA by ultrasound days offset')),
                ('est_fetal_weight', models.DecimalField(decimal_places=2, help_text='Units in grams.', max_digits=8, verbose_name='Estimated fetal weight')),
                ('est_edd', models.DateField(help_text='EDD', validators=[edc_base.model.validators.date.date_not_before_study_start, edc_base.model.validators.date.date_not_future], verbose_name='Estimated date of delivery')),
                ('edd_confirmed', models.DateField(help_text='EDD Confirmed. Derived variable.', verbose_name='EDD Confirmed.')),
                ('ga_confirmed', models.IntegerField(help_text='must be less than 7days.', verbose_name='GA confirmed from ultrasound initial date')),
                ('amniotic_fluid_volume', models.CharField(choices=[('0', '0'), ('1', '1')], max_length=3, verbose_name='Amniotic fluid volume?')),
                ('maternal_visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='td_maternal.MaternalVisit')),
            ],
            options={
                'verbose_name': 'Maternal Ultra Sound Initial',
            },
            managers=[
                ('entry_meta_data_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
