# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 14:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('td_maternal', '0001_initial'),
        ('td_infant', '0001_initial'),
        ('td_appointment', '__first__'),
        ('td_registration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='infantbirth',
            name='maternal_labour_del',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='td_maternal.MaternalLabourDel', verbose_name="Mother's delivery record"),
        ),
        migrations.AddField(
            model_name='infantbirth',
            name='registered_subject',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='td_registration.RegisteredSubject'),
        ),
        migrations.AddField(
            model_name='infantarvprophmod',
            name='infant_arv_proph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='td_infant.InfantArvProph'),
        ),
        migrations.AddField(
            model_name='infantarvproph',
            name='infant_visit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='td_infant.InfantVisit'),
        ),
        migrations.AddField(
            model_name='historicalvaccinesreceived',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalvaccinesreceived',
            name='infant_fu_immunizations',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='td_infant.InfantFuImmunizations'),
        ),
        migrations.AddField(
            model_name='historicalvaccinesmissed',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalvaccinesmissed',
            name='infant_fu_immunizations',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='td_infant.InfantFuImmunizations'),
        ),
        migrations.AddField(
            model_name='historicalinfantvisit',
            name='appointment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='td_appointment.Appointment'),
        ),
        migrations.AddField(
            model_name='historicalinfantvisit',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalinfantvaccines',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalinfantvaccines',
            name='infant_birth_feed_vaccine',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='td_infant.InfantBirthFeedingVaccine'),
        ),
        migrations.AddField(
            model_name='historicalinfantoffstudy',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalinfantoffstudy',
            name='infant_visit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='td_infant.InfantVisit'),
        ),
        migrations.AddField(
            model_name='historicalinfantfunewmeditems',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalinfantfunewmeditems',
            name='infant_fu_med',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='td_infant.InfantFuNewMed'),
        ),
        migrations.AddField(
            model_name='historicalinfantfudxitems',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalinfantfudxitems',
            name='infant_fu_dx',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='td_infant.InfantFuDx'),
        ),
        migrations.AddField(
            model_name='historicalinfantbirth',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalinfantbirth',
            name='maternal_labour_del',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='td_maternal.MaternalLabourDel'),
        ),
        migrations.AddField(
            model_name='historicalinfantbirth',
            name='registered_subject',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='td_registration.RegisteredSubject'),
        ),
        migrations.AddField(
            model_name='historicalinfantarvprophmod',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalinfantarvprophmod',
            name='infant_arv_proph',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='td_infant.InfantArvProph'),
        ),
        migrations.AlterUniqueTogether(
            name='vaccinesreceived',
            unique_together=set([('received_vaccine_name', 'infant_fu_immunizations')]),
        ),
        migrations.AlterUniqueTogether(
            name='vaccinesmissed',
            unique_together=set([('missed_vaccine_name', 'infant_fu_immunizations')]),
        ),
        migrations.AlterUniqueTogether(
            name='infantvaccines',
            unique_together=set([('infant_birth_feed_vaccine', 'vaccination', 'vaccine_date')]),
        ),
        migrations.AlterUniqueTogether(
            name='infanttrisomies',
            unique_together=set([('trisomies', 'congenital_anomalies')]),
        ),
        migrations.AlterUniqueTogether(
            name='infantskin',
            unique_together=set([('skin', 'congenital_anomalies')]),
        ),
        migrations.AlterUniqueTogether(
            name='infantrespiratorydefect',
            unique_together=set([('respiratory_defect', 'congenital_anomalies')]),
        ),
        migrations.AlterUniqueTogether(
            name='infantrenal',
            unique_together=set([('renal', 'congenital_anomalies')]),
        ),
        migrations.AlterUniqueTogether(
            name='infantotherabnormalityitems',
            unique_together=set([('other_abnormalities', 'congenital_anomalies')]),
        ),
        migrations.AlterUniqueTogether(
            name='infantmusculoskeletal',
            unique_together=set([('musculo_skeletal', 'congenital_anomalies')]),
        ),
        migrations.AlterUniqueTogether(
            name='infantmouthupgi',
            unique_together=set([('mouth_up_gi', 'congenital_anomalies')]),
        ),
        migrations.AlterUniqueTogether(
            name='infantmalegenital',
            unique_together=set([('male_genital', 'congenital_anomalies')]),
        ),
        migrations.AlterUniqueTogether(
            name='infantlowergi',
            unique_together=set([('lower_gi', 'congenital_anomalies')]),
        ),
        migrations.AlterUniqueTogether(
            name='infantfudxitems',
            unique_together=set([('fu_dx', 'infant_fu_dx')]),
        ),
        migrations.AlterUniqueTogether(
            name='infantfemalegenital',
            unique_together=set([('female_genital', 'congenital_anomalies')]),
        ),
        migrations.AlterUniqueTogether(
            name='infantfacialdefect',
            unique_together=set([('facial_defect', 'congenital_anomalies')]),
        ),
        migrations.AlterUniqueTogether(
            name='infantcns',
            unique_together=set([('cns', 'congenital_anomalies')]),
        ),
        migrations.AlterUniqueTogether(
            name='infantcleftdisorder',
            unique_together=set([('cleft_disorder', 'congenital_anomalies')]),
        ),
        migrations.AlterUniqueTogether(
            name='infantcardiodisorder',
            unique_together=set([('cardio_disorder', 'congenital_anomalies')]),
        ),
        migrations.AlterUniqueTogether(
            name='infantarvprophmod',
            unique_together=set([('infant_arv_proph', 'arv_code')]),
        ),
    ]
