# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-05 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('td_maternal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maternalultrasoundfu',
            name='cerebellum',
        ),
        migrations.RemoveField(
            model_name='maternalultrasoundfu',
            name='cistema_magna',
        ),
        migrations.RemoveField(
            model_name='maternalultrasoundfu',
            name='hl',
        ),
        migrations.RemoveField(
            model_name='maternalultrasoundfu',
            name='lateral_ventricle',
        ),
        migrations.RemoveField(
            model_name='maternalultrasoundfu',
            name='malformations',
        ),
        migrations.RemoveField(
            model_name='maternalultrasoundfu',
            name='malformations_other',
        ),
        migrations.RemoveField(
            model_name='maternalultrasoundinitial',
            name='cerebellum',
        ),
        migrations.RemoveField(
            model_name='maternalultrasoundinitial',
            name='cistema_magna',
        ),
        migrations.RemoveField(
            model_name='maternalultrasoundinitial',
            name='hl',
        ),
        migrations.RemoveField(
            model_name='maternalultrasoundinitial',
            name='lateral_ventricle',
        ),
        migrations.RemoveField(
            model_name='maternalultrasoundinitial',
            name='malformations',
        ),
        migrations.RemoveField(
            model_name='maternalultrasoundinitial',
            name='malformations_other',
        ),
    ]
