# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 14:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('td_lab', '0001_initial'),
        ('td_maternal', '0001_initial'),
        ('td_infant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maternalrequisition',
            name='maternal_visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='td_maternal.MaternalVisit'),
        ),
        migrations.AddField(
            model_name='maternalrequisition',
            name='panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='td_lab.Panel'),
        ),
        migrations.AddField(
            model_name='infantrequisition',
            name='infant_visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='td_infant.InfantVisit'),
        ),
        migrations.AddField(
            model_name='infantrequisition',
            name='panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='td_lab.Panel'),
        ),
        migrations.AddField(
            model_name='historicalmaternalrequisition',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmaternalrequisition',
            name='maternal_visit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='td_maternal.MaternalVisit'),
        ),
        migrations.AddField(
            model_name='historicalmaternalrequisition',
            name='panel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='td_lab.Panel'),
        ),
        migrations.AddField(
            model_name='historicalinfantrequisition',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalinfantrequisition',
            name='infant_visit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='td_infant.InfantVisit'),
        ),
        migrations.AddField(
            model_name='historicalinfantrequisition',
            name='panel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='td_lab.Panel'),
        ),
        migrations.AddField(
            model_name='historicalaliquot',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='aliquot',
            unique_together=set([('parent_identifier', 'count')]),
        ),
        migrations.AlterUniqueTogether(
            name='maternalrequisition',
            unique_together=set([('maternal_visit', 'panel_name', 'is_drawn')]),
        ),
        migrations.AlterUniqueTogether(
            name='infantrequisition',
            unique_together=set([('infant_visit', 'panel_name', 'is_drawn')]),
        ),
    ]
