from .base_infant_scheduled_modeladmin import BaseInfantScheduleModelAdmin
from .infant_birth_admin import InfantBirthAdmin
from .infant_death_report_admin import InfantDeathReportAdmin
from .infant_off_study_admin import InfantOffStudyAdmin
from .infant_visit_admin import InfantVisitAdmin