#from .appointment_visit_crf_view_mixin import AppointmentSubjectVisitCRFViewMixin
# from .locator_results_actions_view_mixin import LocatorResultsActionsViewMixin
from .marquee_view_mixin import MarqueeViewMixin
from .dashboard_mixin import DashboardMixin
